{
  "uuid": "2689eba7-8a23-449b-a56c-2fc63bc041da",
  "path": "/lib/python3.12/lib2to3/fixes/__pycache__/fix_zip.cpython-312.pyc",
  "size": 1977,
  "modified": "2025-05-28T17:29:55.215456920Z",
  "created": "2025-05-28T17:29:55.215456920Z",
  "sha256_hash": "ceec3d773734a9a57bf614ddb06390b28993cc867c88e331e2a08d59f0230cb9",
  "file_type": {
    "Other": "pyc"
  },
  "permissions": 33188,
  "is_executable": false,
  "is_signed": false,
  "code_signature": null,
  "bundle_info": null,
  "scan_timestamp": "2025-06-01T18:47:09.183730173Z"
}