{
  "uuid": "28874a95-f10b-44a4-81bc-1fb980d4e30b",
  "path": "/usr/lib/python3.12/lib2to3/fixes/__pycache__/fix_exitfunc.cpython-312.pyc",
  "size": 3569,
  "modified": "2025-05-28T17:29:55.207457025Z",
  "created": "2025-05-28T17:29:55.207457025Z",
  "sha256_hash": "a8685c506897dce23acb332fadcb2639de958ded18cc2c1d19876bbd0b57ce44",
  "file_type": {
    "Other": "pyc"
  },
  "permissions": 33188,
  "is_executable": true,
  "is_signed": false,
  "code_signature": null,
  "bundle_info": null,
  "scan_timestamp": "2025-06-01T18:46:04.911374355Z"
}