{
  "uuid": "2bdbfdaa-a5cb-4fd3-b09f-2c4a4274174a",
  "path": "/lib/python3/dist-packages/paramiko/__pycache__/ssh_exception.cpython-312.pyc",
  "size": 9408,
  "modified": "2025-02-15T08:51:43Z",
  "created": "2025-05-09T05:07:27.157786642Z",
  "sha256_hash": "74b3cf960a7b9623f94c14291e616da0b334a73bd854c915d65823ec7324626d",
  "file_type": {
    "Other": "pyc"
  },
  "permissions": 33188,
  "is_executable": false,
  "is_signed": false,
  "code_signature": null,
  "bundle_info": null,
  "scan_timestamp": "2025-06-01T18:46:33.726235673Z"
}