{
  "uuid": "63e32d5a-ce46-400b-a5d3-2aa2ff617bf0",
  "path": "/lib/python3.12/lib2to3/fixes/__pycache__/fix_types.cpython-312.pyc",
  "size": 2271,
  "modified": "2025-05-28T17:29:55.214456934Z",
  "created": "2025-05-28T17:29:55.214456934Z",
  "sha256_hash": "0613da9ac7d98033c7b4ae827dbb765cb24bd31f689bfaca177eadf857766457",
  "file_type": {
    "Other": "pyc"
  },
  "permissions": 33188,
  "is_executable": false,
  "is_signed": false,
  "code_signature": null,
  "bundle_info": null,
  "scan_timestamp": "2025-06-01T18:47:09.183901622Z"
}