{
  "uuid": "6be6a99e-0a4b-4473-b3e5-8aec4232253e",
  "path": "/lib/python3.12/test/test_exception_group.py",
  "size": 34843,
  "modified": "2025-02-04T14:48:35Z",
  "created": "2025-05-28T17:29:48.017551434Z",
  "sha256_hash": "5b61e18f565a58637c5d07ea3bf4879ab0a9756638a114d1943e24349e8a792f",
  "file_type": "Script",
  "permissions": 33188,
  "is_executable": false,
  "is_signed": false,
  "code_signature": null,
  "bundle_info": null,
  "scan_timestamp": "2025-06-01T18:47:08.354012963Z"
}