{
  "uuid": "7a7130f1-2969-4264-b7d3-eb47f3acdc1f",
  "path": "/lib/python3/dist-packages/mako/__pycache__/exceptions.cpython-312.pyc",
  "size": 14744,
  "modified": "2025-02-15T08:51:42Z",
  "created": "2025-05-09T05:07:26.986789251Z",
  "sha256_hash": "6ed57f5ad2eab04b68700e92a9706d2376c0f88bed098d7a4c700ee05417c9b7",
  "file_type": {
    "Other": "pyc"
  },
  "permissions": 33188,
  "is_executable": false,
  "is_signed": false,
  "code_signature": null,
  "bundle_info": null,
  "scan_timestamp": "2025-06-01T18:46:34.298192991Z"
}