{
  "uuid": "ab84b072-9f8b-4742-8ce1-2f9345fa72f1",
  "path": "/lib/python3/dist-packages/requests/__pycache__/exceptions.cpython-312.pyc",
  "size": 6991,
  "modified": "2025-02-15T08:12:13Z",
  "created": "2025-05-09T05:07:27.353783651Z",
  "sha256_hash": "ba272d85970448c893bee6c862590679b6c7170698ba13c64965cc8abf248fda",
  "file_type": {
    "Other": "pyc"
  },
  "permissions": 33188,
  "is_executable": false,
  "is_signed": false,
  "code_signature": null,
  "bundle_info": null,
  "scan_timestamp": "2025-06-01T18:46:34.014204507Z"
}