{
  "uuid": "b9c26494-db79-46a9-8c25-f9439c677a26",
  "path": "/usr/lib/python3.12/xml/sax/__pycache__/_exceptions.cpython-312.pyc",
  "size": 6217,
  "modified": "2025-05-09T05:11:42.148894801Z",
  "created": "2025-05-09T05:11:42.148894801Z",
  "sha256_hash": "34060074d4193ac91998ac9ab14a5e36991efad0dbb55d46ffec1c699fa59a03",
  "file_type": {
    "Other": "pyc"
  },
  "permissions": 33188,
  "is_executable": true,
  "is_signed": false,
  "code_signature": null,
  "bundle_info": null,
  "scan_timestamp": "2025-06-01T18:46:04.844435984Z"
}