{
  "uuid": "bdb4de6a-66cc-4217-9f49-3bd31e42727b",
  "path": "/usr/lib/python3/dist-packages/attr/__pycache__/exceptions.cpython-312.pyc",
  "size": 3548,
  "modified": "2025-02-15T08:11:54Z",
  "created": "2025-05-09T05:07:26.535796133Z",
  "sha256_hash": "606c49ca55cd384d9318c3fa39fb2f9b373a0bde5fcc20f6708a3edf19473a26",
  "file_type": {
    "Other": "pyc"
  },
  "permissions": 33188,
  "is_executable": true,
  "is_signed": false,
  "code_signature": null,
  "bundle_info": null,
  "scan_timestamp": "2025-06-01T18:45:25.561649720Z"
}