{
  "uuid": "d1a290b4-501f-4040-9db6-3fd472fd3836",
  "path": "/lib/python3/dist-packages/nacl/__pycache__/exceptions.cpython-312.pyc",
  "size": 2999,
  "modified": "2025-02-15T08:51:42Z",
  "created": "2025-05-09T05:07:27.017788778Z",
  "sha256_hash": "c0ac8718efe84716b139db0232fe2be5f1bf1f4efde753f6353d62f4ca0795d3",
  "file_type": {
    "Other": "pyc"
  },
  "permissions": 33188,
  "is_executable": false,
  "is_signed": false,
  "code_signature": null,
  "bundle_info": null,
  "scan_timestamp": "2025-06-01T18:46:34.288697645Z"
}