{
  "uuid": "ea4ca21d-ffd0-419f-a761-b7c07746838a",
  "path": "/lib/python3.12/lib2to3/fixes/__pycache__/fix_filter.cpython-312.pyc",
  "size": 3607,
  "modified": "2025-05-28T17:29:55.207457025Z",
  "created": "2025-05-28T17:29:55.207457025Z",
  "sha256_hash": "4ce5e81654d29a798b760ad84f93696e4177b0040996c25bd47c768d0d0a7426",
  "file_type": {
    "Other": "pyc"
  },
  "permissions": 33188,
  "is_executable": false,
  "is_signed": false,
  "code_signature": null,
  "bundle_info": null,
  "scan_timestamp": "2025-06-01T18:47:09.184516419Z"
}